name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  verify-project-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: Spring Boot build with Toxiproxy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17.0
          distribution: 'adopt'
          java-package: 'jdk'

      - name: Check Maven Version
        run: mvn --version

      - name: Build project and run Integration tests
        run: mvn clean verify